### PR TITLE
[Proposal] delegate closed check to underlying session

### PR DESCRIPTION
**Pull request by tpitale**

### CODE REVIEW

**Comment by tpitale** [comment]
This is related to #7. It provides a simple interface to ask the underlying session if it is closed. It does not alter any of the looping/threading logic that already exists.

**Comment by mfazekas** [comment]
Do you have real word use for this? 
I'd be much more happy to integrate something that's been proved to be usefull vs something that we think might be usefull.

**Comment by tpitale** [comment]
The use case I outlined in #7.

Basically, I'm having a case where the underlying session is dying because the connection is closed by the end server.

I need to know when that happens so I can take action to kill processes that use the tunnel. Right now the gateway/tunnel acts like everything is fine. My processes just hang forever.

**Comment by mfazekas** [comment]
Can you post some code? I think i understand the usecase, but the devil is in details, so it would be good to see some code achieving what you want.

**Comment by tpitale** [comment]
Like this? This is a simplified version of what I'm doing in production right now. I have a thread that loops over my set of tunnels (wrappers around `Gateway` instances). The tunnel closes the gateway if the gateway's session is closed.

```ruby
Thread.new do
  loop do
    tunnels.each do |t|
      t.disconnect if t.gateway.closed?
    end

    sleep 10
  end
end
```

**Comment by tpitale** [comment]
I dunno … it just seems odd that the gateway acts like everything is fine if the underlying session is closed. That seems like a bug to me. I'm trying to make it easy by suggesting it as a feature. Maybe that's the wrong approach.

**Comment by tpitale** [comment]
If I was going to fix the bug in net-ssh-gateway, I would change this code:

```ruby
    def initiate_event_loop!
      @active = true

      @thread = Thread.new do
        while @active
          @session_mutex.synchronize do
            @session.process(@loop_wait)
            raise IOError.new("Session closed") if @session.closed?
          end
          Thread.pass
        end
      end
      @thread.abort_on_exception = true
    end
```

**Comment by tpitale** [comment]
But that's a kill-everything sort of scenario because of `abort_on_exception`.

**Comment by tpitale** [comment]
Or maybe this is better:

```ruby
   def initiate_event_loop!
      @active = true

      @thread = Thread.new do
        while @active
          @session_mutex.synchronize do
            @session.process(@loop_wait)
          end
          shutdown! if @session.closed?
          Thread.pass
        end
      end
    end
```

**Comment by tpitale** [comment]
I can try that in production to see how it runs.

**Comment by tpitale** [comment]
Actually, that might be a problem because `shutdown!` waits for `@thread.join` … so that's no good.

**Comment by tpitale** [comment]
Ugh, threads in Ruby.

**Comment by tpitale** [comment]
How about this:

```ruby
    def initiate_event_loop!
      @active = true

      initiate_session_watcher!

      @thread = Thread.new do
        while @active
          @session_mutex.synchronize do
            @session.process(@loop_wait)
          end
          Thread.pass
        end
      end
    end

    def initiate_session_watcher!
      Thread.new do
        while @active
          shutdown! if @session.closed?

          sleep @watcher_wait
        end
      end
    end
```

**Comment by tpitale** [comment]
I could go either way. Or none at all. I'm happy to just subclass gateway in my own code and close this.

**Comment by tpitale** [comment]
This PR was just the most simple way I could think that would allow a user of the gateway to handle watching for abnormal closing without changing net-ssh-gateway too much.

**Comment by mfazekas** [comment]
@tpitale thanks for looking into it. Can we clarify the original issue?

So you connect to a gateway you start some services but the gateway closed. But the existing tunnels port are not closed, and kept around forever?
This sounds like more a bug than we need a feature for. But let me try to repro it to see i fully understand the issue.

Miklos

**Comment by tpitale** [comment]
I'll open a new issue for cleaner discussion.

**Pull request closed without merging**
